### ISSUE TITLE
7-3-9-8

### ISSUE THREAD

**Issue by Speretta** [ardamavi/Artificial-Intelligence-Tic-Tac-Toe#1]
1 | 2 | 3
  - | - | -
  4 | 5 | 6
  - | - | -
  7 | 8 | 9 

X's turn: 7

  1 | 2 | 3
  - | - | -
  4 | O | 6
  - | - | -
  X | 8 | 9 

X's turn: 3

  O | 2 | X
  - | - | -
  4 | O | 6
  - | - | -
  X | 8 | 9 

X's turn: 9

  O | O | X
  - | - | -
  4 | O | 6
  - | - | -
  X | 8 | X 

X's turn: 8

  O | O | X
  - | - | -
  4 | O | 6
  - | - | -
  X | X | X 

Win: X
Arda Mavi - ardamavi.com
The End !

**Comment by ardamavi** [comment]
Thank you for your feedback.
We can change the scoring system in `probability` Function.
